global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'dynamic-service-discovery'
    file_sd_configs:
    - files:
      - /prometheus/sd.json # enable dynamic service discovery